"""Repository ports consumed by application services.

The protocols deliberately expose domain operations rather than SQLAlchemy expressions. ORM-backed
entities remain the current domain records for API compatibility, but query construction, locking,
and database-specific conflict handling are confined to adapters.
"""

from __future__ import annotations

from collections.abc import Iterable
from datetime import datetime
from typing import Any, Protocol, TypeVar

from app.models import (
    Application,
    CandidateProfile,
    CvAnalysisRun,
    CvExport,
    CvImport,
    CvRecommendation,
    CvRecommendationEvidence,
    CvVariant,
    CvVariantVersion,
    DiscoveryJobSource,
    DiscoveryMatchResult,
    DiscoveryNotification,
    DiscoveryProviderCursor,
    DiscoveryProviderError,
    DiscoverySearchConfiguration,
    DiscoverySearchProfile,
    DiscoverySearchRun,
    DocumentExport,
    GeneratedDocument,
    Job,
    JobVersion,
    MatchRecommendationDecision,
    MatchVersion,
    ProfileVersion,
    StoredFile,
    User,
)

T = TypeVar("T")


class PersistenceConflict(RuntimeError):
    """A uniqueness or integrity constraint rejected a persistence operation."""


class CandidateRepository(Protocol):
    def get_profile(self, user_id: str, *, lock: bool = False) -> CandidateProfile | None: ...
    def latest_profile_version(self, user_id: str) -> ProfileVersion | None: ...
    def get_profile_version(self, version_id: str, user_id: str) -> ProfileVersion | None: ...
    def list_profile_versions(self, user_id: str) -> list[ProfileVersion]: ...
    def next_profile_version(self, profile_id: str) -> int: ...
    def sync_skills(self, profile: CandidateProfile) -> None: ...
    def replace_extended_profile(self, profile_id: str, snapshot: dict[str, Any]) -> None: ...


class CvRepository(Protocol):
    def get_import(
        self, import_id: str, user_id: str, *, lock: bool = False
    ) -> CvImport | None: ...
    def list_imports(self, user_id: str) -> list[CvImport]: ...
    def expired_imports(self, cutoff: datetime) -> list[CvImport]: ...
    def file_for_import(self, import_id: str) -> StoredFile | None: ...
    def record_upload_attempt(self, user_id: str, limit: int, now: datetime) -> bool: ...


class JobRepository(Protocol):
    def get(self, job_id: str) -> Job | None: ...
    def list_jobs(self, *, limit: int = 100) -> list[Job]: ...
    def duplicate_candidates(
        self, source: str, external_id: str | None, normalized_url: str | None, content_hash: str
    ) -> list[tuple[str, str | None, str | None, str]]: ...
    def latest_version(self, job_id: str) -> JobVersion | None: ...
    def next_version(self, job_id: str) -> int: ...
    def save_version(self, job: Job) -> JobVersion: ...


class ApplicationRepository(Protocol):
    def get_owned(
        self, application_id: str, user_id: str, *, lock: bool = False
    ) -> Application | None: ...
    def get_for_job(
        self, user_id: str, job_id: str, *, lock: bool = False
    ) -> Application | None: ...
    def list_owned(self, user_id: str) -> list[Application]: ...
    def list_history(self, application_id: str) -> list[Any]: ...
    def next_document_version(self, application_id: str) -> int: ...
    def list_documents(
        self, application_id: str, *, latest_valid: bool = False
    ) -> list[GeneratedDocument]: ...


class DiscoveryRepository(Protocol):
    def get_search_profile(self, user_id: str) -> DiscoverySearchProfile | None: ...
    def list_configurations(self, user_id: str) -> list[DiscoverySearchConfiguration]: ...
    def get_configuration(
        self, configuration_id: str, user_id: str | None = None, *, lock: bool = False
    ) -> DiscoverySearchConfiguration | None: ...
    def list_runs(self, user_id: str, limit: int) -> list[DiscoverySearchRun]: ...
    def scheduled_run_exists(self, scheduled_key: str) -> bool: ...
    def due_configurations(self, now: datetime) -> list[DiscoverySearchConfiguration]: ...
    def provider_cursor(
        self, configuration_id: str, provider: str, *, lock: bool = False
    ) -> DiscoveryProviderCursor | None: ...
    def list_provider_cursors(self, user_id: str) -> list[DiscoveryProviderCursor]: ...
    def list_provider_errors(
        self, user_id: str, *, limit: int = 50
    ) -> list[DiscoveryProviderError]: ...
    def latest_match(self, user_id: str, job_id: str) -> DiscoveryMatchResult | None: ...
    def match_for_run(self, run_id: str, job_id: str) -> DiscoveryMatchResult | None: ...
    def get_match(
        self, match_id: str, user_id: str, *, lock: bool = False
    ) -> DiscoveryMatchResult | None: ...
    def list_ranked_matches(
        self, user_id: str, filters: dict[str, Any]
    ) -> list[tuple[DiscoveryMatchResult, Job]]: ...
    def notification_exists(self, user_id: str, key: str) -> bool: ...
    def list_notifications(
        self, user_id: str, *, unread_only: bool = False
    ) -> list[DiscoveryNotification]: ...
    def get_notification(
        self, notification_id: str, user_id: str
    ) -> DiscoveryNotification | None: ...
    def job_source(self, provider: str, external_id: str | None) -> DiscoveryJobSource | None: ...
    def job_by_normalized_url(self, value: str) -> Job | None: ...
    def job_by_content_hash(self, value: str) -> Job | None: ...
    def likely_job(self, company: str, title: str, city: str | None) -> Job | None: ...
    def configuration_named(
        self, user_id: str, name: str
    ) -> DiscoverySearchConfiguration | None: ...
    def sync_provider_configurations(
        self, user_id: str, settings: dict[str, dict[str, Any]]
    ) -> None: ...


class RecommendationRepository(Protocol):
    def latest_analysis_inputs(
        self, user_id: str, job_id: str
    ) -> tuple[ProfileVersion | None, DiscoveryMatchResult | None]: ...
    def get_analysis(
        self, analysis_id: str, user_id: str, *, lock: bool = False
    ) -> CvAnalysisRun | None: ...
    def list_analyses(self, user_id: str, job_id: str | None = None) -> list[CvAnalysisRun]: ...
    def recommendations(self, analysis_id: str) -> list[CvRecommendation]: ...
    def recommendation_with_analysis(
        self, recommendation_id: str, user_id: str, *, lock: bool = False
    ) -> tuple[CvRecommendation, CvAnalysisRun] | None: ...
    def evidence(self, recommendation_id: str) -> list[CvRecommendationEvidence]: ...
    def pending_recommendation_count(self, analysis_id: str) -> int: ...
    def get_variant(self, variant_id: str, user_id: str) -> CvVariant | None: ...
    def variant_for_analysis(self, user_id: str, analysis_id: str) -> CvVariant | None: ...
    def list_variants(self, user_id: str, job_id: str | None = None) -> list[CvVariant]: ...
    def latest_variant_version(self, variant_id: str) -> CvVariantVersion | None: ...
    def export(self, version_id: str, format_name: str) -> CvExport | None: ...
    def export_for_download(self, export_id: str, user_id: str) -> CvExport | None: ...
    def export_keys(self, variant_id: str) -> list[str]: ...


class CoverLetterRepository(Protocol):
    def get(
        self, document_id: str, user_id: str, *, lock: bool = False
    ) -> GeneratedDocument | None: ...
    def list_letters(self, user_id: str, job_id: str | None = None) -> list[GeneratedDocument]: ...
    def selected_id(self, application_id: str) -> str | None: ...
    def clear_selection(self, application_id: str) -> None: ...
    def export(self, document_id: str, format_name: str) -> DocumentExport | None: ...
    def export_for_download(self, export_id: str, user_id: str) -> DocumentExport | None: ...
    def export_keys(self, document_id: str) -> list[str]: ...


class MatchRepository(Protocol):
    def save_explainable(
        self,
        *,
        result: DiscoveryMatchResult,
        profile_version: ProfileVersion,
        job_version: JobVersion,
        analysis: dict[str, Any],
        engine_version: str,
    ) -> MatchVersion: ...
    def latest_version(self, result_id: str) -> MatchVersion | None: ...
    def record_decision(
        self, result_id: str, actor_id: str, decision: str, reason: str | None = None
    ) -> MatchRecommendationDecision | None: ...


class UnitOfWork(Protocol):
    @property
    def candidates(self) -> CandidateRepository: ...
    @property
    def cvs(self) -> CvRepository: ...
    @property
    def jobs(self) -> JobRepository: ...
    @property
    def applications(self) -> ApplicationRepository: ...
    @property
    def discovery(self) -> DiscoveryRepository: ...
    @property
    def recommendations(self) -> RecommendationRepository: ...
    @property
    def cover_letters(self) -> CoverLetterRepository: ...
    @property
    def matches(self) -> MatchRepository: ...

    def get_user(self, user_id: str) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def add(self, entity: object) -> None: ...
    def add_all(self, entities: Iterable[object]) -> None: ...
    def delete(self, entity: object) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, entity: object, *, lock: bool = False) -> None: ...
    def detach(self, entity: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def audit(
        self,
        user_id: str,
        action: str,
        entity_type: str,
        entity_id: str,
        metadata: dict[str, Any] | None = None,
    ) -> None: ...
